tests/ui/parser/pragma_unknown.sol, tests/ui/parser/pragma_unknown.stderr
This PR adds a syntax unit test to check the case where the pragma has a version but not the `solidity` pragma.
=> Add syntax test pragma solidity

crates/parse/src/parser/item.rs
Allow parsing semver version separately
=> feat: make parse_semver_req public

crates/sema/src/ast_passes.rs, tests/ui/parser/break_continue_outside_loop.sol, tests/ui/parser/break_continue_outside_loop.stderr, tests/ui/typeck/unchecked_block.sol, tests/ui/typeck/unchecked_block.stderr
This PR adds an AST validation to check for nested `unchecked` blocks.
=> AST validate unchecked nested blocks

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/cli/src/utils.rs, crates/interface/src/diagnostics/context.rs, crates/interface/src/diagnostics/mod.rs, crates/interface/src/globals.rs, crates/interface/src/lib.rs, crates/interface/src/session.rs, crates/interface/src/span.rs, examples/src/parser.rs
Install the rayon pool together with session globals in Session::enter instead of in CLI only; this enables library users to use `sema` and any other `rayon` usage
cc @ferranbt https://t.me/paradigm_solar/100
=> fix: install rayon pool in Session::enter

crates/sema/src/ast_passes.rs, tests/ui/parser/contract_function_shared_name.sol, tests/ui/parser/contract_function_shared_name.stderr
This PR adds an AST validation check similar to [this](https://github.com/ethereum/solidity/blob/df01dcc7b759f53ba45811979d3286562eab7846/libsolidity/analysis/SyntaxChecker.cpp#L385) which verifies that a function does not have the same name as the contract.
Note, eventually this can be merged into a specific AST contract level checker.
=> AST validate that a contract does not have a function with contract name

crates/sema/src/ast_passes.rs, tests/ui/typeck/invalid_placeholder.sol, tests/ui/typeck/invalid_placeholder.stderr
implements the placeholder statement item in https://github.com/paradigmxyz/solar/issues/29
=> fix: validate placeholder is within modifier

crates/parse/src/parser/expr.rs
For example `ExprKind::Call`'s span was:
```
my . member (arg) ;
~~~~~
```
now includes the LHS too:
```
my . member (arg) ;
~~~~~~~~~~~~~~~~~
```
=> fix(parser): span of partially-parsed expressions

crates/ast/src/lib.rs, crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/cursor/token.rs, crates/parse/src/lexer/mod.rs, crates/parse/src/lib.rs, crates/parse/src/parser/expr.rs, crates/parse/src/parser/item.rs, crates/parse/src/parser/lit.rs, crates/parse/src/parser/mod.rs, crates/parse/src/parser/stmt.rs, crates/parse/src/parser/ty.rs, crates/parse/src/parser/yul.rs, crates/sema/src/ast_lowering/lower.rs, crates/sema/src/ast_lowering/mod.rs, crates/sema/src/ast_lowering/resolve.rs, crates/sema/src/ast_passes.rs, crates/sema/src/builtins/members.rs, crates/sema/src/builtins/mod.rs, crates/sema/src/eval.rs, crates/sema/src/hir.rs, crates/sema/src/lib.rs, crates/sema/src/parse.rs, crates/sema/src/stats.rs, crates/sema/src/ty/abi.rs, crates/sema/src/ty/common.rs, crates/sema/src/ty/mod.rs, crates/sema/src/ty/ty.rs, examples/src/parser.rs
Before: `use solar_ast::{ast::Item, visit::Visitor};`, `use solar_parse::ast::Item;` (visitor not available)
After: `use solar_ast::{Item, visit::Visitor};`, `use solar_parse::ast::{Item, visit::Visitor};` (identical + other modules are available)
=> refactor!: re-export ast::* internal module

crates/ast/src/ast/ty.rs, crates/sema/src/parse.rs, crates/sema/src/ty/abi.rs, crates/sema/src/ty/ty.rs
Currently they are in the same struct but re-use none of eachother's implementations.
=> refactor: split Ty printers

crates/sema/src/ast_lowering/resolve.rs, tests/ui/abi/mapping_getters.sol, tests/ui/abi/mapping_getters.stdout
Ref https://github.com/ethereum/solidity/blob/9d7cc42bc1c12bb43e9dccf8c6c36833fdfcbbca/libsolidity/ast/Types.cpp#L2887-L2891
=> fix: exclude arrays from mapping getter returns

crates/ast/src/ast/mod.rs, crates/ast/src/token.rs, crates/parse/src/lexer/mod.rs, crates/parse/src/parser/expr.rs, crates/parse/src/parser/item.rs, crates/parse/src/parser/mod.rs, crates/parse/src/parser/stmt.rs, crates/parse/src/parser/yul.rs, tests/ui/parser/unusual_doc_comments.sol, tests/ui/parser/yul/erc20.yul, tests/ui/parser/yul/solc_generated.yul
Rewrites how the parser handles comments/docs to allow doc-comments in any place in source code, like comments.
=> feat(parser): allow doc-comments anywhere

crates/sema/src/ast_passes.rs, tests/ui/resolve/modifier_without_placeholder.sol, tests/ui/resolve/modifier_without_placeholder.stderr
https://github.com/paradigmxyz/solar/issues/29
=> feat: modifier definitions must have a placeholder

crates/ast/src/ast/item.rs, crates/sema/src/ast_passes.rs, tests/ui/resolve/func_modifiers.sol, tests/ui/resolve/func_modifiers.stderr
Implemented the following lines from syntax checker 
https://github.com/ethereum/solidity/blob/a62a455039120da834fd5faac2e0db8fc222c10d/libsolidity/analysis/SyntaxChecker.cpp#L474C1-L479C1
=> feat: syntax checker for functions with modifiers

crates/sema/src/stats.rs, tests/ui/stats/ast.stderr
=> fix: display order in AST stats

crates/cli/src/lib.rs, crates/interface/src/globals.rs, crates/interface/src/session.rs, crates/parse/src/lexer/mod.rs, crates/parse/src/parser/mod.rs
Keep previous behavior for `enter`, add a separate function to install thread pool.
=> fix: add Session::enter_parallel

crates/ast/src/ast/stmt.rs, crates/ast/src/visit.rs, crates/parse/src/parser/stmt.rs, crates/sema/src/ast_lowering/resolve.rs, crates/sema/src/hir/mod.rs, crates/sema/src/hir/visit.rs, crates/sema/src/stats.rs, tests/ui/resolve/try_scopes.sol
Also tweaks the representation by grouping both the successful and unsuccessful clauses in the same array.
Fixes #196.
=> fix: correctly resolve try/catch scopes

crates/interface/src/diagnostics/context.rs, crates/interface/src/diagnostics/emitter/human.rs, crates/interface/src/diagnostics/emitter/json.rs, crates/interface/src/diagnostics/emitter/mod.rs
Instead of wrapping an inner Dcx which contains unnecessary state.
=> chore: make SilentEmitter wrap DynEmitter

crates/sema/src/ast_lowering/lower.rs
https://github.com/ethereum/solidity/blob/a1506a38a8d683992477c76b00715eb70dbf94b2/libsolidity/ast/Types.cpp#L2866
=> fix: variable getter functions are external

crates/cli/Cargo.toml, crates/cli/src/utils.rs, crates/solar/Cargo.toml
Cuts binary size in half by removing 13 dependencies, including `regex`.
=> feat: allow compiling out tracing-subscriber

CONTRIBUTING.md, crates/sema/src/lib.rs, crates/sema/src/parse.rs, examples/src/AnotherCounter.sol, examples/src/hir.rs, examples/src/lib.rs
- access Hir from calling ParsingContext::parse_and_lower_to_hir
=> feat(hir): expose hir from parsing context

crates/sema/src/builtins/mod.rs
The following use of `std::mem::transmute` in `Builtin::from_index` was previously unsound, as there are few layout [guarantees](https://doc.rust-lang.org/reference/type-layout.html#r-layout.repr.rust.layout) made for `repr(Rust)` types. This `transmute` relies on the assumption that an enum has the same alignment as the smallest integer type that can hold all its variants, but `repr(Rust)` enums make no such guarantee.
https://github.com/paradigmxyz/solar/blob/27f20c504cacf59c19c902dc925ff85e49bb1c37/crates/sema/src/builtins/mod.rs#L266-L277
This is fixed by tagging the `Builtin` enum `repr(u8)`, which provides the [guarantees](https://doc.rust-lang.org/reference/type-layout.html#primitive-representation-of-field-less-enums) needed here. I have also added a safety comment explaining the …
=> fix: unsound transmute

crates/ast/src/ast/item.rs, crates/ast/src/visit.rs, crates/parse/src/parser/item.rs, crates/sema/src/ast_lowering/resolve.rs, tests/ui/resolve/import_glob_conflicts.sol, tests/ui/resolve/import_glob_conflicts.stderr
`import * from "x";` is not accepted as an alternative to `import "x";`.
https://docs.soliditylang.org/en/latest/grammar.html#a4.SolidityParser.importDirective
=> fix(parser)!: glob imports require an alias

crates/config/src/lib.rs, crates/interface/src/source_map/file_resolver.rs
It can be that multiple "--include-path"s point to the same path, or that a remapping target is an absolute path, so the for loop would push the same file multiple times which would fail the check below.
=> fix: dedup resolved files

Cargo.lock, crates/interface/src/source_map/mod.rs, crates/parse/src/lexer/mod.rs, crates/parse/src/parser/lit.rs
Currently we reject hex rational literals in the lexer, but they are passed on to the parser which then panics.
Fixes https://github.com/foundry-rs/foundry/issues/10287.
=> fix(parser): don't panic when parsing hex rationals

crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/cursor/tests.rs, crates/parse/src/lexer/cursor/token.rs, crates/parse/src/lexer/mod.rs, tests/ui/parser/no_unknown_prefix.sol
Identifiers are allowed to be attached to string literals.
~~Based on https://github.com/paradigmxyz/solar/pull/259.~~
=> fix(parser)!: remove RawTokenKind::UnknownPrefix

crates/ast/src/ast/item.rs, crates/ast/src/ast/lit.rs, crates/ast/src/ast/mod.rs, crates/interface/src/span.rs, crates/parse/src/parser/lit.rs
- re-export `either` in ast as it's used in the public API
- UserDefinableOperator::to_str
- impl fmt::Display for Lit
- improve fmt::Debug for LitKind::Str
- treat literal parse errors as non fatal using the LitKind::Err variant
=> feat: pretty printing utilities

Cargo.lock, crates/ast/Cargo.toml, crates/ast/src/ast/expr.rs, crates/ast/src/ast/lit.rs, crates/parse/src/parser/lit.rs, crates/parse/src/parser/yul.rs, crates/sema/src/ty/abi.rs
Currently multiple string literals of the same kind get concatenated in the parser, without leaving trace in the AST.
Add an extra field to `LitKind::Str` that stores any extra literals that were concatenated into the current literal.
=> feat(ast)!: store concatenated string literals

crates/parse/src/lexer/mod.rs
This makes it so that the vector never has to reallocate on 99% of regular files. I have yet to see a file that has lower than a ratio of 4, whereas a lot of files have between ~4.5 and 8.
=> perf(lexer): double tokens capacity estimate

.github/workflows/bench.yml, .github/workflows/ci.yml, .gitmodules, benches/README.md, benches/src/lib.rs, tools/tester/src/lib.rs
Cargo will recursively fetch submodules in `cargo install`, `[dependencies] git = ""`... unless `update=none` is specified.
See: https://github.com/rust-lang/cargo/issues/4247#issuecomment-1149178736
=> chore: add update=none to submodules

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/utils.rs, crates/config/Cargo.toml, crates/solar/Cargo.toml, dist-workspace.toml
mimalloc consistently is performing equal to or better than jemalloc, is smaller in binary size, is more portable and is faster to compile
=> perf: add and default to using mimalloc

crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/mod.rs
We still use `Chars` internally to handle UTF-8 correctly, but everywhere else we use `u8` instead of `char`.
Improves `Cursor` performance by 10-30%.
=> perf(lexer): deal with bytes instead of chars in Cursor

crates/sema/src/ast_passes.rs, tests/ui/resolve/address_checksums.sol, tests/ui/resolve/address_checksums.stderr, tests/ui/resolve/denominations.sol, tests/ui/resolve/denominations.stderr
Implements literal checks from solc
These checks are not implemented because I don't really know if they are relevant:
- Seems like a weird check? Or at least something for typeck https://github.com/ethereum/solidity/blob/9c0098b221556e4df56c892d7280bfb5b7e10c0d/libsolidity/analysis/TypeChecker.cpp#L3740-L3745
- I assume we already have this handled https://github.com/ethereum/solidity/blob/9c0098b221556e4df56c892d7280bfb5b7e10c0d/libsolidity/analysis/TypeChecker.cpp#L3781-L3782
Closes #284
=> feat: literal checks

crates/data-structures/src/index.rs
We need to stringify the ident otherwise the doc will literally just include `$name`
=> docs: fix `newtype_index!` generated doc comments

crates/cli/src/lib.rs, crates/config/src/opts.rs
Adds a flag to disable emitting warning diagnostics.
In the future, we should consider following rustc's format with flags `-A` and `-D` to allow and deny
warnings, respectively. In `rustc`, `-Awarnings` is equivalent to `--no-warnings`.
Additionally, `-Dwarnings` would treat warnings
as errors.
Ref #170 since it is blocked because we currently don't support disabling warnings
=> feat: `--no-warnings`

crates/interface/src/diagnostics/context.rs, crates/sema/src/hir/mod.rs, crates/sema/src/typeck/mod.rs, tests/ui/parser/payable_fallback_without_receive.sol, tests/ui/parser/payable_fallback_without_receive.stderr
https://github.com/ethereum/solidity/blob/03e2739809769ae0c8d236a883aadc900da60536/libsolidity/analysis/ContractLevelChecker.cpp#L544C1-L554C2
=> feat: warn when payable fallback function found but no receive function

crates/parse/src/lexer/cursor/mod.rs
Cursor performance:
- `inline(never)` on `eat_until`: -7% to +21%
- nothing: -15% to +15%
- `inline(never)` on `line_comment`: -1% to +26%
Not entirely sure why inlining even just the few instructions that call out to memchr can have such a huge impact on overall performance of `Cursor`, even when memchr isn't even called.
=> perf(lexer): add eat_until

crates/sema/src/typeck/mod.rs, tests/ui/parser/payable_fallback_without_receive.sol, tests/ui/parser/payable_fallback_without_receive.stderr
Conditions mismatch https://github.com/ethereum/solidity/blob/d6a396eed7c60322ec22039b77b8ed1bc79be35b/libsolidity/analysis/ContractLevelChecker.cpp#L583
=> fix(sema): don't warn 3628 if no interface functions

crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/cursor/tests.rs
~+10-12% faster Cursor: https://codspeed.io/paradigmxyz/solar/branches/dani%2Fcursor-slice-iter
=> perf(lexer): use slice::Iter instead of Chars in Cursor

crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/cursor/tests.rs
Windows, unlike other OS, uses CRLF (`\r\n`) as end-of-line delimiter. As the lexer relies on the end-of-line when handling `//`/`///` single line comments, this creates a cross-platform inconsistent behavior (the final `\r` ends up included in the comment parsed, see  #315 ).
This PR adds a test for this hedge case and a suggested fix (reusing memchr ability to match 2 different bytes in a given haystack)
=> fix: windows eol lexing

crates/ast/src/ast/stmt.rs, crates/ast/src/visit.rs, crates/parse/src/parser/stmt.rs, crates/sema/src/ast_lowering/resolve.rs, crates/sema/src/hir/mod.rs
necessary for the formatter to properly handle comments such as `comment9`, which are placed after a closing brace `}` and the keyword `catch`:
```solidity
// comment7
try unknown.empty() {
// comment8
unknown.doSomething();
} /* comment9 */ catch /* comment10 */ Error(string memory) {
unknown.handleError();
} catch /* comment11 */ Panic(uint256) {
unknown.handleError();
}
```
=> chore: add span to `TryCatchClause`

benches/README.md, benches/benches/criterion.rs, benches/benches/iai.rs, benches/criterion.out, benches/src/lib.rs
Removing `Session` initialization from the parser benchmarks, since it's a one-time initialization just like `enter` currently. This is changed in https://github.com/paradigmxyz/solar/pull/379, so making these changes here to remove noise from that PR.
=> chore(benches): extract Session initialization to its own benchmark

crates/sema/src/ast_lowering/mod.rs, crates/sema/src/ast_lowering/resolve.rs
Clean up symbol resolution by fully using a single `self` everywhere and re-using scopes resources.
=> perf: pool symbol resolver scopes, refactor

crates/ast/src/visit.rs
A bug report for ⁠`forge-lint` revealed that the AST visitor was not traversing array size exprs. This means that any issues within those expressions aren't caught.
- https://github.com/foundry-rs/foundry/issues/11392
ensure array size expres are visited
=> fix(ast): visit array size

crates/interface/src/session.rs, crates/sema/src/compiler.rs
Thankfully `ThreadPoolBuilder::build_scoped` can be entirely re-implemented by ourselves, using `Arc` + `spawn` instead of `std::thread::scope`, avoiding having to create a new thread pool every time `enter` is called.
=> perf(interface): cache thread pool inside of session

crates/ast/src/token.rs, crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/cursor/tests.rs, crates/parse/src/lexer/cursor/token.rs, crates/parse/src/lexer/mod.rs
- Updated `next_token` method in `Lexer` to directly use the result of `bump()` without attempting to glue tokens.
- Added new raw token kinds for various operators: `EqEq`, `Le`, `Ge`...
- Updated `Cursor` to handle multi-character operator tokens and their corresponding raw token kinds.
- Removed the `glue` methods from `TokenKind` and `Token` impl (no longer needed)
Closes #477
=> refactor(lexer): Inline token glueing into Cursor

crates/parse/src/lexer/cursor/mod.rs, crates/parse/src/lexer/mod.rs
These methods generally shouldn't be called directly since we provide an Iterator implementation.
=> chore!: rename lexer methods to slop

crates/parse/src/lexer/cursor/char_info.rs, crates/parse/src/lexer/cursor/mod.rs
Turns out lookup table is faster due to less instructions and branches, which outweighs the hit from having one in the first place. CC @malik672
=> perf(lexer): use lookup tables for char info

crates/ast/src/ast/mod.rs, crates/ast/src/ast/yul.rs, crates/ast/src/visit.rs, crates/parse/src/parser/yul.rs
=> refactor(ast): boxed `yul::StmtKind::For` to reduce the size of `yul::Stmt`

crates/ast/src/token.rs, crates/parse/src/parser/item.rs, crates/parse/src/parser/mod.rs
Even though token is `Copy` and 16 bytes, it won't be passed in 2x8 byte registers but rather on the stack. We can separate the fields of the struct and instead write it as `(u64, u64)` to allow passing `Token` in registers.
=> perf(parser): pass Token in registers

crates/interface/src/globals.rs, crates/interface/src/lib.rs
This should not be used directly. There isn't really a reason for it to be public since Session should be used instead.
=> chore(interface)!: make SessionGlobals private

crates/interface/src/source_map/analyze.rs
Estimate capacity at `len / 32`. In most cases this reallocates 0 or 1 times.
=> perf(interface): estimate capacity for SourceFile::lines

Cargo.lock, benches/Cargo.toml, benches/benches/criterion.rs, benches/src/lib.rs
Note that the performance regressions are not real in the sense that the previous benchmarks would allocate on the first benchmark iteration and then just do lookups in the subsequent ones, whereas the benchmarks now get a full new session on each iteration, which means we don't reuse anything from previous iterations.
Closes #520
=> bench: lowering benchmarks

crates/sema/src/parse.rs
Add `ParsingCtxt::force_resolve_all_imports` which allows delaying/manually resolving imports in all sources in the context. This is useful for fixing foundry-rs/foundry#11668.
=> feat(sema): allow delaying/manual import resolution

crates/sema/src/ast_lowering/resolve.rs
The only difference in the two branches is `resolved`, which can be extracted in its own `if` expression.
=> chore(sema): simplify perform_imports

crates/parse/src/parser/mod.rs, tests/ui/parser/close_delimeter.sol, tests/ui/parser/close_delimeter.stderr, tests/ui/parser/close_delimeter2.sol, tests/ui/parser/close_delimeter2.stderr
The while loop in `parse_seq_to_before_tokens ` was exiting early on the close parentheses emitting an error for the missing semi. Since `parse_struct` also `expect`'s semis, it was hitting the panic in `expected_one_of_not_found`. 
`parse_seq_to_end` already `expect`s a close bracket, so it's okay to use `check_noexpect` and prevents the close bracket from appearing in the error message: "ERROR: expected `;` or `}`, found `)`"
Addresses 2nd panic in https://github.com/foundry-rs/foundry/issues/12001
=> fix: do not break on close paren for struct
