paradigmxyz/solar

Cargo.lock
Cargo.toml
crates/ast/src/ast/semver.rs
deny.toml

Add more `to_semver` for converting to `::semver` types.

feat: add more semver compat

---

crates/ast/src/visit.rs
crates/sema/src/ast_passes.rs

feat: return ControlFlow from AST visitor methods

---

crates/sema/src/ast_passes.rs
tests/ui/parser/break_continue_outside_loop.sol
tests/ui/parser/break_continue_outside_loop.stderr
tests/ui/typeck/unchecked_block.sol
tests/ui/typeck/unchecked_block.stderr

Follow-up https://github.com/paradigmxyz/solar/pull/116
@ferranbt Sorry I realized these should be `` ` `` backticks not apostrophes `'`

test: add some more tests

---

crates/parse/src/parser/item.rs
crates/parse/src/parser/mod.rs
crates/sema/src/ast_passes.rs
tests/ui/typeck/empty_struct.sol
tests/ui/typeck/empty_struct.stderr

closes https://github.com/paradigmxyz/solar/issues/118

better error for struct without any fields

---

Cargo.lock
crates/data-structures/src/cycle.rs
crates/data-structures/src/lib.rs
crates/interface/src/diagnostics/mod.rs
crates/sema/Cargo.toml
crates/sema/src/lib.rs
crates/sema/src/ty/abi.rs
crates/sema/src/ty/mod.rs
crates/sema/src/ty/ty.rs
tests/ui/typeck/nested_struct_issue_129.sol
tests/ui/typeck/recursive_function_parameter.sol
tests/ui/typeck/recursive_function_parameter.stderr
tests/ui/typeck/recursive_structs.sol
tests/ui/typeck/recursive_structs.stderr
tests/ui/typeck/recursive_types.sol
tests/ui/typeck/recursive_types.stderr

Fixes https://github.com/paradigmxyz/solar/issues/129

fix: properly handle recursive types

---

crates/interface/src/lib.rs
crates/interface/src/pos.rs
crates/interface/src/source_map/analyze.rs
crates/interface/src/source_map/file.rs
crates/interface/src/source_map/mod.rs
crates/interface/src/span.rs
crates/parse/src/lexer/mod.rs
crates/parse/src/lexer/unicode_chars.rs

I'm not sure why this exists in the first place, it's only imported to provide the methods.

chore!: remove Pos trait

---

crates/interface/src/source_map/file.rs
crates/interface/src/source_map/mod.rs

plus non-generic inner function in `SourceMap::new_source_file`

feat: add some FileName functions

---

crates/sema/src/ast_passes.rs
tests/ui/resolve/func_visibility.sol
tests/ui/resolve/func_visibility.stderr
tests/ui/resolve/receive_func.sol
tests/ui/resolve/receive_func.stderr

https://github.com/DaniPopes/solidity/blob/de1a017ccb935d149ed6bcbdb730d89883f8ce02/libsolidity/analysis/ContractLevelChecker.cpp#L171C1-L193C3
(omitted the checks that are already implemented in the pipeline)

feat: receive function validation

---

crates/sema/src/ast_passes.rs
tests/ui/resolve/placeholder_unchecked.sol
tests/ui/resolve/placeholder_unchecked.stderr

https://github.com/ethereum/solidity/blob/03e2739809769ae0c8d236a883aadc900da60536/libsolidity/analysis/SyntaxChecker.cpp#L368C1-L379C2

feat: check placeholders inside unchecked blocks

---

Cargo.lock
crates/interface/src/diagnostics/message.rs
crates/macros/src/visitor.rs
crates/sema/Cargo.toml
crates/sema/src/ast_lowering/resolve.rs
crates/sema/src/hir/mod.rs
crates/sema/src/hir/visit.rs

Ref https://github.com/paradigmxyz/solar/issues/63
This also updated Emit/Revert and removes CallOptions ExprKind for simpler handling after

feat: implement minimal HIR visitor

---

crates/sema/src/ast_passes.rs
tests/ui/resolve/virtual_modifier.sol

fix: don't check placeholders in virtual modifiers

---

crates/interface/src/pos.rs
crates/interface/src/source_map/mod.rs
crates/interface/src/span.rs

Plus some more docs on how Span works

feat: improve SourceMap helpers for Span to source

---

Cargo.lock
Cargo.toml
crates/interface/Cargo.toml
crates/interface/src/source_map/file.rs
crates/interface/src/source_map/file_resolver.rs
crates/interface/src/source_map/mod.rs
crates/interface/src/source_map/tests.rs
crates/parse/src/parser/mod.rs
crates/sema/src/ast_lowering/mod.rs
crates/sema/src/hir/mod.rs
crates/sema/src/parse.rs

Also fix handling of `parent` in `resolve_file`.

feat!: refactor FileResolver to allow custom current_dir

---

crates/cli/Cargo.toml
crates/config/Cargo.toml
crates/config/build.rs

By moving version string and build.rs logic to solar-config, the displayed features also changed

fix: correct features in version string

---

crates/sema/src/parse.rs
tests/ui/resolve/unknown_import.sol
tests/ui/resolve/unknown_import.stderr

Instead of the entire import directive.

fix: point resolution errors to the import string

---

crates/ast/src/token.rs
crates/cli/src/lib.rs
crates/config/src/lib.rs
crates/sema/src/parse.rs
tools/tester/src/lib.rs

CompilerStage::Parsed now does not resolve imports anymore.

feat!: add CompilerStage::ParsedAndImported

---

crates/ast/src/token.rs

Found here https://github.com/paradigmxyz/solar/pull/153

fix(ast): BinOpToken::Caret is BinOpKind::BitXor

---

crates/parse/src/parser/lit.rs

fix(parser): align number parsing with solc

---

Cargo.lock
crates/interface/Cargo.toml
crates/interface/src/source_map/mod.rs
crates/sema/Cargo.toml
crates/sema/src/ty/interner.rs
crates/sema/src/ty/mod.rs
crates/sema/src/ty/ty.rs

Shouldn't matter that much for performance, but we are removing the `scc` dependency.

chore: misc map cleanups

---

crates/parse/src/parser/lit.rs

Validated with https://github.com/paradigmxyz/solar/issues/284

feat(parser): accept non-checksummed addresses, to be validated later

---

.github/workflows/ci.yml
Cargo.toml
clippy.toml
crates/interface/src/diagnostics/emitter/mod.rs

chore: rust 1.86

---

tests/ui/resolve/try_scopes.sol

Already fixed with #200.
Fixes https://github.com/paradigmxyz/solar/issues/217.

test: add another try catch resolve test

---

tests/ui/resolve/global_storage_param.sol

Already fixed previously.
Fixes https://github.com/paradigmxyz/solar/issues/218.

test: add a test for global storage param

---

crates/sema/src/ast_lowering/resolve.rs
tests/ui/resolve/shadowed_vars.sol
tests/ui/resolve/shadowed_vars.stderr

Fixes https://github.com/paradigmxyz/solar/issues/207.

fix(sema): correct variable declaration scopes

---

crates/sema/src/builtins/members.rs
crates/sema/src/builtins/mod.rs
tests/ui/resolve/selfdestruct.sol

Fixes https://github.com/paradigmxyz/solar/issues/215.

fix(sema): declare selfdestruct builtin

---

crates/parse/src/parser/mod.rs

Fixes https://github.com/paradigmxyz/solar/issues/308.

fix(parser): clear docs if not consumed immediatly

---

crates/ast/src/ast/item.rs
crates/ast/src/visit.rs
crates/parse/src/parser/item.rs
crates/parse/src/parser/ty.rs
crates/sema/src/ast_lowering/lower.rs
tests/ui/stats/ast.stderr

Add and populate a span in FunctionHeader
Closes #317

feat: add span in FunctionHeader

---

crates/interface/src/source_map/file_resolver.rs

Absolute paths may be inserted manually into the source map outside of the resolver, so we should also try to fetch the unresolved absolute path before canonicalizing

fix: try absolute paths in file resolver too

---

crates/sema/src/ast_lowering/lower.rs
crates/sema/src/ast_lowering/mod.rs
crates/sema/src/ast_lowering/resolve.rs
crates/sema/src/hir/mod.rs
crates/sema/src/hir/visit.rs
tests/ui/resolve/base_constructor.sol

Follow-up https://github.com/paradigmxyz/solar/pull/322

fix: visit modifiers in hir visitor

---

crates/ast/src/ast/item.rs
crates/ast/src/ast/mod.rs
crates/ast/src/ast/ty.rs
crates/ast/src/visit.rs
crates/interface/src/span.rs
crates/parse/src/parser/item.rs
crates/sema/src/ast_lowering/lower.rs
crates/sema/src/ast_lowering/resolve.rs
crates/sema/src/ast_passes.rs
crates/sema/src/span_visitor.rs
crates/sema/src/stats.rs
crates/sema/src/ty/abi.rs
crates/sema/src/ty/ty.rs
tests/ui/parser/span_visitor.stderr

avoids dummy spans
cc @0xrusowsky

chore: use Option<StateMutability> in the AST

---

crates/ast/src/ast/item.rs
crates/sema/src/hir/mod.rs

While using HIR, found that some additional helpers could improve the user experience with functions : )

feat(sema): add helper methods to Function

---

.github/workflows/bench.yml
.github/workflows/ci.yml
.github/workflows/release.yml

ci: update to `actions/checkout@v5`

---

crates/sema/src/ast_lowering/linearize.rs

- Don't remove_empty before loop
- Remove candidates inside of the remove_empty inside the loop

chore: clean up contract inheritance linearization

---

crates/ast/src/ast/lit.rs
crates/interface/src/lib.rs
crates/interface/src/symbol.rs
crates/parse/src/parser/lit.rs

Towards https://github.com/paradigmxyz/solar/pull/414.

feat!: add ByteSymbol, use in LitKind::Str

---

.gitmodules
benches/README.md
crates/ast/src/ast/item.rs
crates/ast/src/ast/lit.rs
crates/ast/src/ast/semver.rs
crates/interface/src/source_map/file_resolver.rs
crates/interface/src/symbol.rs
crates/parse/src/lexer/cursor/mod.rs
crates/parse/src/lexer/mod.rs
crates/parse/src/parser/expr.rs
crates/parse/src/parser/item.rs
crates/parse/src/parser/lit.rs
crates/parse/src/parser/stmt.rs
crates/parse/src/parser/yul.rs
crates/sema/src/ast_lowering/linearize.rs
crates/sema/src/ast_lowering/resolve.rs
crates/sema/src/builtins/members.rs
crates/sema/src/builtins/mod.rs
crates/sema/src/eval.rs
crates/sema/src/ty/abi.rs
crates/sema/src/ty/mod.rs
tools/tester/src/solc/solidity.rs

chore(meta): update solidity links

---

crates/cli/src/lib.rs
crates/cli/src/signal_handler.rs
crates/solar/src/main.rs

chore: update signal handler

---

Cargo.lock
Cargo.toml
crates/cli/src/lib.rs
crates/config/Cargo.toml
crates/config/src/lib.rs
crates/config/src/opts.rs
crates/interface/src/diagnostics/context.rs
crates/interface/src/diagnostics/emitter/human.rs
crates/interface/src/diagnostics/emitter/json.rs
crates/interface/src/diagnostics/emitter/rustc.rs
crates/interface/src/lib.rs
crates/interface/src/session.rs
crates/interface/src/source_map/file.rs
crates/interface/src/source_map/mod.rs
crates/interface/src/source_map/tests.rs

Plus some source map cleanups.
Closes https://github.com/paradigmxyz/solar/issues/467.

feat(interface)!: impl Default for Session, create dcx from opts

---

crates/sema/src/ast_lowering/linearize.rs
crates/sema/src/ast_lowering/resolve.rs
crates/sema/src/hir/mod.rs
tests/ui/resolve/impossible_linearization.sol
tests/ui/resolve/impossible_linearization.stderr

See https://github.com/foundry-rs/foundry/issues/11504.

fix(sema): handle linearization failure fallout

---

crates/parse/src/lexer/cursor/mod.rs

Almost always a win because most strings don't have escapes, so it's just a memchr till the first quote character.

perf(lexer): use eat_until_either in eat_string

---

crates/parse/src/lib.rs
crates/parse/src/parser/mod.rs

feat(parser): introduce `Recovered` enum to improve code readability

---

crates/interface/src/span.rs

Small win, +0% - +3%: https://codspeed.io/paradigmxyz/solar/branches/dani%2Fpack-span-2
We still want to keep it aligned to 4 bytes (`#[repr(packed(4))]`) to keep it identical to before and to avoid increasing the size of the AST, and we need to implement `Ord` manually instead of deriving it for the u64.

perf(interface): pack Span into a u64

---

Cargo.lock
benches/Cargo.toml
benches/benches/criterion.rs
benches/benches/iai.rs
benches/src/lib.rs

bench: use meta crate

---

crates/ast/src/lib.rs
crates/cli/src/lib.rs
crates/config/src/lib.rs
crates/data-structures/src/lib.rs
crates/interface/src/lib.rs
crates/macros/src/lib.rs
crates/parse/src/lib.rs
crates/sema/src/lib.rs
crates/solar/src/lib.rs

```rust
error[E0557]: feature has been removed
--> ...
|
L | #![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
|                                      ^^^^^^^^^^^^ feature has been removed
|
= note: removed in 1.58.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
= note: merged into `doc_cfg`
```

chore: remove feature(doc_auto_cfg)

---

crates/sema/src/compiler.rs

fix(sema)!: do not expose mutable Session access while entered

---

crates/sema/src/parse.rs

Test https://github.com/paradigmxyz/solar/pull/548.

test: add unit test and debug assertion for sources inconsistency

---

crates/parse/src/lexer/cursor/mod.rs
crates/parse/src/parser/lit.rs

The lexer already raises an error but the parser didn't handle the 1st panic in https://github.com/foundry-rs/foundry/issues/12001

fix(parser): neg. exp. empty check, disallow plus
